spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ${DB_H2_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: false
    
flyway:
  schemas: PRUEBA
  locations: classpath:db/migration
  baselineOnMigrate: true
  
spring.jpa.show-sql: false
spring.jpa.properties.hibernate.format_sql: false

logging:
  level:
    root: INFO
    com.fricton.inditex.prices: DEBUG